name: laura.ro
markdown: kramdown
google_analytics: UA-88877773-1
gems: [jekyll-paginate, jekyll-feed]
paginate: 1
paginate_path: /blog/:num
url: http://laura.ro
description: random rants
name: Laura Vasilescu RSS
author: Laura
